apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: buildah-multiarch
spec:
  params:
    - default:
        - linux/x86_64
        - linux/arm64/v8
      name: buildahPlatforms
      type: array
    - default: 'https://github.com/smartinus44/devfile-sample-code-with-quarkus.git'
      name: gitRepositoryURL
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/test/code-with-quarkus'
      name: outputContainerImage
      type: string
    - default: ./workspace/output/src/main/docker/Dockerfile.jvm
      name: containerfilepath
      type: string
  tasks:
    - name: multiarch-buildah
      params:
        - name: buildahVersion
          value: latest
        - name: containerfilepath
          value: $(params.containerfilepath)
        - name: buildahPlatforms
          value:
            - '$(params.buildahPlatforms[*])'
        - name: outputContainerImage
          value: $(params.outputContainerImage)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: multiarch-buildah
      workspaces:
        - name: src
          subPath: src
          workspace: scratch
        - name: containers
          subPath: containers
          workspace: scratch
    - name: git-clone
      params:
        - name: url
          value: $(params.gitRepositoryURL)
        - name: revision
          value: be2fc686f21c3933a95d17e065577b1c23424679
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:89fc179cd82c8ddf010af89213d3f224b99863fa21deaea5c26ab0b4c214d01b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          subPath: src
          workspace: scratch
  workspaces:
    - name: scratch
  finally: []
