apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: multiarch-without-emulation
spec:
  params:
    - default: 'https://github.com/smartinus44/buildah-multiarchitecture-build'
      name: gitRepositoryURL
      type: string
    - default: 'quay.io/rh_ee_symartin/multiarch_test/dummyimage:2.0-$(uname -m)'
      name: outputContainerImage
      type: string
  tasks:
    - name: debug-arch
      taskRef:
        kind: Task
        name: debug-arch
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.outputContainerImage)
        - name: BUILDER_IMAGE
          value: 'quay.io/buildah/stable:v1.35'
        - name: STORAGE_DRIVER
          value: overlay
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: '--platform=$(uname -m)'
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: scratch
    - name: git-clone
      params:
        - name: url
          value: $(params.gitRepositoryURL)
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:84c7b5115270e63701e8b8768b9d0908c91a88d22ddeb1a11e0411f648abbb26
        - name: userHome
          value: /home/git
      runAfter:
        - debug-arch
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: scratch
  workspaces:
    - name: scratch
      optional: false
  finally: []
