apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc-amd64
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
