apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-build-and-push-to-the-host-arch
  namespace: test
spec:
  params:
    - name: buildahVersion
      type: string
    - name: containerfilepath
      type: string
    - name: buildahPlatform
      type: string
    - name: outputContainerImage
      type: string
    - name: outputContainerTag
      type: string
  steps:
    - args:
        - $(params.buildahPlatform)
      computeResources: {}
      env:
        - name: TARGET_IMAGE
          value: $(params.outputContainerImage)
        - name: TAG
          value: $(params.outputContainerTag)
      image: 'quay.io/containers/buildah:$(params.buildahVersion)'
      name: buildah
      script: |
        #!/bin/bash

        set -Eeuo pipefail

        function build () {
          echo "========================================================="
          echo " buildah build $TARGET_IMAGE for ${1:-default}"
          echo "========================================================="
          echo

          extra_args=""
          if [ -n "${1:-}" ]; then
            extra_args="$extra_args --platform $1"
          fi
          if [ -n "$(params.containerfilepath)" ]; then
            extra_args="$extra_args --file $(params.containerfilepath)"
          fi

          buildah bud --storage-driver vfs --manifest tekton -t $TARGET_IMAGE $extra_args .
          echo
        }

        function push () {
          echo "========================================================="
          echo " buildah push $1"
          echo "========================================================="
          echo
          buildah manifest push --storage-driver vfs --all tekton "docker://$1"
          echo
        }


        build "$(params.buildahPlatform)"

        push "$TARGET_IMAGE:$TAG-$(uname -m)"

        exit 0      
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
        privileged: true
      workingDir: /src
  workspaces:
    - mountPath: /src
      name: src
    - mountPath: /var/lib/containers
      name: containers
